/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Return liveness + app version. No filesystem access (AD-9).
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Doc
         * @description Import an uploaded PDF; return its ``doc_id`` + metadata.
         */
        post: operations["upload_doc_api_docs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{doc_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Doc File
         * @description Stream a stored document's PDF bytes. Storage owns the path (AR-9).
         *
         *     Unknown/unresolvable id → 404; a corrupt on-disk record → 500. Both use the
         *     single ``{ "detail" }`` envelope (AR-11).
         */
        get: operations["get_doc_file_api_docs__doc_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/docs/{doc_id}/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Annotations
         * @description Return a document's saved annotation set for hydrate-on-open (AR-6, H9).
         *
         *     The response body is the bare list (H9); the on-disk envelope is stripped
         *     only inside storage. An imported-but-unannotated doc returns ``[]`` (200,
         *     not 404). Unknown/unresolvable id → 404; a corrupt or unknown-version disk
         *     file → 500. Both use the single ``{ "detail" }`` envelope (AR-11).
         */
        get: operations["get_annotations_api_docs__doc_id__annotations_get"];
        /**
         * Put Annotations
         * @description Overwrite the document's full annotation set, atomically (AR-7, H6).
         *
         *     The request/response body is the bare list (H9); the on-disk envelope
         *     is added/stripped only inside storage. No history, undo, or merge here:
         *     this overwrites with exactly what it received.
         */
        put: operations["put_annotations_api_docs__doc_id__annotations_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Annotation
         * @description One annotation (AD-5). Stored keyed by ``id`` in the client store and,
         *     in Epic 3, persisted to ``annotations.json``. ``group_id`` ties the split
         *     halves of a two-page selection together (``None`` for a single-page mark).
         *     ``body`` is non-null only for memo/comment.
         */
        Annotation: {
            /** Id */
            id: string;
            /** Doc Id */
            doc_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "highlight" | "underline" | "pen" | "memo" | "comment";
            /** Group Id */
            group_id?: string | null;
            /** Anchor */
            anchor: components["schemas"]["TextAnchor"] | components["schemas"]["RectAnchor"] | components["schemas"]["PathAnchor"];
            style: components["schemas"]["Style"];
            /** Body */
            body?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** Body_upload_doc_api_docs_post */
        Body_upload_doc_api_docs_post: {
            /** File */
            file: string;
        };
        /**
         * Doc
         * @description API representation of an imported document = ``doc_id`` + its metadata.
         */
        Doc: {
            /** Filename */
            filename: string;
            /** Title */
            title?: string | null;
            /** Page Count */
            page_count: number;
            /** Added */
            added: string;
            /** Last Opened */
            last_opened: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Doc Id */
            doc_id: string;
        };
        /**
         * HealthStatus
         * @description Liveness response for ``GET /api/health``. Also carries the app version
         *     (single source: ``server/pyproject.toml`` via ``app.version``).
         */
        HealthStatus: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * PathAnchor
         * @description Anchor over a freehand pen stroke (Story 2.5).
         */
        PathAnchor: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "path";
            /** Page Index */
            page_index: number;
            /** Points */
            points: components["schemas"]["Point"][];
        };
        /**
         * Point
         * @description A normalized point on a page (``[0,1]`` fractions), for pen paths.
         */
        Point: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * Rect
         * @description A normalized rect on a page: ``[0,1]`` fractions of the scale-1.0 page
         *     box, canonical (``x0<=x1, y0<=y1``), top-left origin, y-down.
         */
        Rect: {
            /** X0 */
            x0: number;
            /** Y0 */
            y0: number;
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
        };
        /**
         * RectAnchor
         * @description Anchor over a single rectangular region (box-select, memo).
         */
        RectAnchor: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rect";
            /** Page Index */
            page_index: number;
            rect: components["schemas"]["Rect"];
        };
        /**
         * Style
         * @description Visual style. ``color`` is a token-name or hex resolved by the client;
         *     ``stroke_width`` is pen-only (``None`` for text/region marks);
         *     ``alpha`` is transparency 0..1 for pen strokes (``None`` = render at the
         *     default highlighter opacity); ``collapsed`` is memo-only (``None``/``False``
         *     = expanded, the default; ``True`` = show only the memo's first line).
         *     Additive + optional (AD-8).
         */
        Style: {
            /** Color */
            color: string;
            /** Stroke Width */
            stroke_width?: number | null;
            /** Alpha */
            alpha?: number | null;
            /** Collapsed */
            collapsed?: boolean | null;
        };
        /**
         * TextAnchor
         * @description Anchor over runs of selected text (highlight / underline / comment). The
         *     ``rects`` are the per-line boxes from the native Selection API.
         */
        TextAnchor: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Page Index */
            page_index: number;
            /** Rects */
            rects: components["schemas"]["Rect"][];
            /** Text */
            text: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            /** Detail */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    upload_doc_api_docs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_doc_api_docs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Doc"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_doc_file_api_docs__doc_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored PDF bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description No document with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The stored document is unreadable. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_annotations_api_docs__doc_id__annotations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"][];
                };
            };
            /** @description No document with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The stored annotation set is unreadable. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    put_annotations_api_docs__doc_id__annotations_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Annotation"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"][];
                };
            };
            /** @description No document with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The annotation set could not be saved. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
